In [13]:
a = 0
for i in range(10):
    a += i
    if i > 0:
        break

In [14]:
a

1

In [1]:
import numpy as np

In [16]:
a = 13910

In [17]:
b = np.arange(0,13910)
print(b.shape)

(13910,)


In [18]:
print(b)

[    0     1     2 ... 13907 13908 13909]


In [29]:
vector_a = np.array([1,1])
vector_b = np.array([0.5,0.0])

In [30]:
np.linalg.norm(vector_a)

1.4142135623730951

In [31]:
np.linalg.norm(vector_b)

0.5

In [34]:
np.linalg.norm(vector_b - vector_a)

1.118033988749895

In [71]:
x = np.array([[1,2],[3,4]])
print(x)
print(x.shape)

[[1 2]
 [3 4]]
(2, 2)


In [66]:
np.repeat(x, 2)

array([1, 1, 2, 2, 3, 3, 4, 4])

In [67]:
np.repeat(x, 3, axis=1)

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [70]:
np.repeat(x, 2, axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [72]:
np.reshape(x,(4,1))

array([[1],
       [2],
       [3],
       [4]])

In [55]:
array1 = np.array([1, 7, 8, 2, 0.1, 3, 15, 2.5])

result = np.argsort(array1)

print(result)

print(array1[result][:3])

[4 0 3 7 5 1 2 6]
[0.1 1.  2. ]


In [67]:
(13910*423 + 234) // 13910

423

In [70]:
(13910*123 + 543) % 13910

543

In [6]:
a = [[1,3],[5,6]]
print(a)

[[1, 3], [5, 6]]


In [8]:
for i in range(len(a)):
    if 3 in a[i]:
        a[i].remove(3)

In [9]:
print(a)

[[1], [5, 6]]


In [36]:
a = np.array([2,-10,8,9])
print(a)

[  2 -10   8   9]


In [37]:
b = np.array([1,3,2,-8])
print(b)

[ 1  3  2 -8]


In [38]:
c = np.array([a,b])
print(c)
print(c.T)

[[  2 -10   8   9]
 [  1   3   2  -8]]
[[  2   1]
 [-10   3]
 [  8   2]
 [  9  -8]]


In [43]:
np.argsort(c, axis=0)

array([[1, 0, 1, 1],
       [0, 1, 0, 0]])

In [40]:
np.argsort(c.T, axis=0).T

array([[1, 0, 2, 3],
       [3, 0, 2, 1]])